config/routes.rb
Restaurante::Application.routes.draw do
  resources :itempedidos

  resources :contas

  resources :conta

  resources :pedidos

  resources :produtos

  resources :clientes

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/conta.rb
class Conta < ActiveRecord::Base
  belongs_to :pedido
end

app/models/contum.rb
class Contum < ActiveRecord::Base
  belongs_to :pedido
end

app/models/itempedido.rb
class Itempedido < ActiveRecord::Base
  belongs_to :pedido
  belongs_to :produto
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :cliente
end

app/models/produto.rb
class Produto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < InheritedResources::Base

	def build_resource_params
        [params.fetch(:cliente, {}).permit(:nomeCliente, :telefone, :cpf)]
    end

end

app/controllers/contas_controller.rb
class ContasController < InheritedResources::Base
	def build_resource_params
        [params.fetch(:conta, {}).permit(:dataAbertura, :valorTotal, :status, :dataFechamento , :pedido_id)]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/itempedidos_controller.rb
class ItempedidosController < InheritedResources::Base
	def build_resource_params
        [params.fetch(:itempedido, {}).permit(:subtotal, :pedido_id, :produto_id)]
    end
end

app/controllers/pedidos_controller.rb
class PedidosController < InheritedResources::Base
	def build_resource_params
        [params.fetch(:pedido, {}).permit(:dataPedido, :situacaoPedido, :cliente_id)]
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < InheritedResources::Base

	def build_resource_params
        [params.fetch(:produto, {}).permit(:descricao, :preco, :quantidade)]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/conta_helper.rb
module ContaHelper
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itempedidos_helper.rb
module ItempedidosHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/clientes/_form.html.haml
= semantic_form_for [@cliente] do |form|
  
  = form.input :nomeCliente, :label => 'Nome'
  = form.input :telefone, :label => 'Telefone'
  = form.input :cpf, :label => 'CPF'
  = form.submit 'Salvar'

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nomecliente</th>
      <th>Cpf</th>
      <th>Telefone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nomeCliente %></td>
        <td><%= cliente.cpf %></td>
        <td><%= cliente.telefone %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Excluir', cliente, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nomeCliente %>
</p>

<p>
  <strong>CPF:</strong>
  <%= @cliente.cpf %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @cliente.telefone %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/contas/_form.html.haml
= semantic_form_for [@conta] do |form|
  
  = form.input :dataAbertura, :label => 'Data de abertura'
  = form.input :valorTotal, :label => 'Valor total' 
  = form.input :status, :label => 'Status' 
  = form.input :dataFechamento, :label => 'Data de fechamento'

  = form.input :pedido, :member_label => :situacaoPedido, :label => 'pedido' 
  = form.submit 'Salvar'

app/views/contas/edit.html.erb
<h1>Editing conta</h1>

<%= render 'form' %>

<%= link_to 'Show', @conta %> |
<%= link_to 'Back', contas_path %>

app/views/contas/index.html.erb
<h1>Listing contas</h1>

<table>
  <thead>
    <tr>
      <th>Dataabertura</th>
      <th>Valortotal</th>
      <th>Status</th>
      <th>Datafechamento</th>
      <th>Pedido</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contas.each do |conta| %>
      <tr>
        <td><%= conta.dataAbertura %></td>
        <td><%= conta.valorTotal %></td>
        <td><%= conta.status %></td>
        <td><%= conta.dataFechamento %></td>
        <td><%= conta.pedido.situacaoPedido %></td>
        <td><%= link_to 'Show', conta %></td>
        <td><%= link_to 'Edit', edit_conta_path(conta) %></td>
        <td><%= link_to 'Excluir', conta, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conta', new_conta_path %>

app/views/contas/new.html.erb
<h1>New conta</h1>

<%= render 'form' %>

<%= link_to 'Back', contas_path %>

app/views/contas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data de abertura:</strong>
  <%= @conta.dataAbertura %>
</p>

<p>
  <strong>Valor total:</strong>
  <%= @conta.valorTotal %>
</p>

<p>
  <strong>Status:</strong>
  <%= @conta.status %>
</p>

<p>
  <strong>Data de fechamento:</strong>
  <%= @conta.dataFechamento %>
</p>

<p>
  <strong>pedido:</strong>
  <%= @conta.pedido.situacaoPedido %>
</p>

<%= link_to 'Edit', edit_conta_path(@conta) %> |
<%= link_to 'Back', contas_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/itempedidos/_form.html.haml
= semantic_form_for [@itempedido] do |form|

  = form.input :subtotal, :label => 'Subtotal'
  
  = form.input :pedido, :member_label => :situacaoPedido, :label => 'Pedido' 
  = form.input :produto, :member_label => :descricao, :label => 'Produto'

  = form.submit 'Salvar'

app/views/itempedidos/edit.html.erb
<h1>Editing itempedido</h1>

<%= render 'form' %>

<%= link_to 'Show', @itempedido %> |
<%= link_to 'Back', itempedidos_path %>

app/views/itempedidos/index.html.erb
<h1>Listing itempedidos</h1>

<table>
  <thead>
    <tr>
      <th>Subtotal</th>
      <th>Pedido</th>
      <th>Produto</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @itempedidos.each do |itempedido| %>
      <tr>
        <td><%= itempedido.subtotal %></td>
        <td><%= itempedido.pedido.situacaoPedido %></td>
        <td><%= itempedido.produto.descricao %></td>
        <td><%= link_to 'Show', itempedido %></td>
        <td><%= link_to 'Edit', edit_itempedido_path(itempedido) %></td>
        <td><%= link_to 'Excluir', itempedido, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Itempedido', new_itempedido_path %>

app/views/itempedidos/new.html.erb
<h1>New itempedido</h1>

<%= render 'form' %>

<%= link_to 'Back', itempedidos_path %>

app/views/itempedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subtotal:</strong>
  <%= @itempedido.subtotal %>
</p>

<p>
  <strong>Pedido:</strong>
  <%= @itempedido.pedido.situacaoPedido %>
</p>

<p>
  <strong>Produto:</strong>
  <%= @itempedido.produto.descricao %>
</p>

<%= link_to 'Edit', edit_itempedido_path(@itempedido) %> |
<%= link_to 'Back', itempedidos_path %>

app/views/pedidos/_form.html.haml
= semantic_form_for [@pedido] do |form|
  
  = form.input :dataPedido, :label => 'Data'
  = form.input :situacaoPedido, :label => 'Situação' 

  = form.input :cliente, :member_label => :nomeCliente, :label => 'Cliente' 
  = form.submit 'Salvar'

app/views/pedidos/edit.html.erb
<h1>Editing pedido</h1>

<%= render 'form' %>

<%= link_to 'Show', @pedido %> |
<%= link_to 'Back', pedidos_path %>

app/views/pedidos/index.html.erb
<h1>Listing pedidos</h1>

<table>
  <thead>
    <tr>
      <th>Datapedido</th>
      <th>Situacaopedido</th>
      <th>Cliente</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pedidos.each do |pedido| %>
      <tr>
        <td><%= pedido.dataPedido %></td>
        <td><%= pedido.situacaoPedido %></td>
        <td><%= pedido.cliente.nomeCliente %></td>

        <td><%= link_to 'Show', pedido %></td>
        <td><%= link_to 'Edit', edit_pedido_path(pedido) %></td>
        <td><%= link_to 'Excluir', pedido, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pedido', new_pedido_path %>

app/views/pedidos/new.html.erb
<h1>New pedido</h1>

<%= render 'form' %>

<%= link_to 'Back', pedidos_path %>

app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @pedido.dataPedido %>
</p>

<p>
  <strong>Situação:</strong>
  <%= @pedido.situacaoPedido %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @pedido.cliente.nomeCliente %>
</p>

<%= link_to 'Edit', edit_pedido_path(@pedido) %> |
<%= link_to 'Back', pedidos_path %>

app/views/produtos/_form.html.haml
= semantic_form_for [@produto] do |form|
  
  = form.input :descricao, :label => 'Descricao'
  = form.input :preco, :label => 'Preco'
  = form.input :quantidade, :label => 'Quantidade'
  = form.submit 'Salvar'

app/views/produtos/edit.html.erb
<h1>Editing produto</h1>

<%= render 'form' %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

app/views/produtos/index.html.erb
<h1>Listing produtos</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Preco</th>
      <th>Quantidade</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.descricao %></td>
        <td><%= produto.preco %></td>
        <td><%= produto.quantidade %></td>
        <td><%= link_to 'Show', produto %></td>
        <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
        <td><%= link_to 'Excluir', produto, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1>New produto</h1>

<%= render 'form' %>

<%= link_to 'Back', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao,:</strong>
  <%= @produto.descricao, %>
</p>

<p>
  <strong>Preco,:</strong>
  <%= @produto.preco, %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @produto.quantidade %>
</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>